AdvancedDict/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("quiz/new", views.generate_quiz, name="generate quiz"),
    path("quiz/<int:quiz_id>", views.get_quiz, name="display quiz"),
    path("quiz/report/<int:quiz_id>", views.report_quiz, name="report quiz"),
    path("reports", views.all_reports, name="reports"),

    #API
    path("edit/<int:word_id>", views.edit, name="edit"),

]

LanguageLearningTool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("AdvancedDict.urls")),
]

AdvancedDict/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from datetime import datetime
# Create your models here.
from . import languageCodes

class diff_choices(models.IntegerChoices):
    EASY = 3, 'Easy'
    NORMAL = 6, 'Normal'
    HARD = 10, 'Hard'
    
class User(AbstractUser):
    pass

class NewWord(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField("New Word", max_length=50)
    translation = models.CharField("Translation", max_length=500)
    translation_edited = models.CharField("Displayed translation", max_length=500)
    sourceLanguage = models.CharField("Source language",max_length=5, choices=languageCodes.languages, default="en")
    targetLanguage = models.CharField("Target language",max_length=5, choices=languageCodes.languages, default="en")
    timestamp = models.DateTimeField(default=datetime.now())
    
    
    def __str__(self) -> str:
        return f'{self.sourceLanguage} {self.text} to {self.targetLanguage} {self.translation}'

class Quiz(models.Model):
    
 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    difficulty = models.IntegerField("Difficulty", choices=diff_choices.choices, default=diff_choices.EASY)
    score = models.PositiveIntegerField(blank=True, null=True)
    timestamp = models.DateTimeField(default=datetime.now())
    questions = models.ManyToManyField(NewWord, related_name="quiz")
    answers = models.ManyToManyField("Answer", related_name="quiz")

    def __str__(self) -> str:
        return f'{self.user} got {self.score} at {self.timestamp.strftime("%d %B %Y %H:%M")}' 
    
    class Meta:
        verbose_name_plural = "Quizes"




    
class Answer(models.Model):
    text = models.CharField("User's answer", max_length=50)
    question = models.ForeignKey(NewWord, related_name="answer", on_delete=models.RESTRICT)
    correct = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.quiz.get()} quiz answered {self.text}'

AdvancedDict/views.py
from django.shortcuts import render

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from django.db import IntegrityError

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse

from django import forms
from django.forms import ModelForm

from django.core.paginator import Paginator


from datetime import datetime

from .models import User, NewWord, Quiz, Answer
from . import languageCodes

import requests, os, json, random
from dotenv import load_dotenv
# export PYTHONPATH=c:/users/admin/appdata/local/programs/python/python311/lib/site-packages

load_dotenv()
API_KEY=os.getenv('API_KEY')


# Forms

class New_word(ModelForm):  
    class Meta:
        model = NewWord
        fields = ("text", "sourceLanguage", "targetLanguage",)
        
        widgets = {
            "text": forms.TextInput(attrs={"class": "form-control", "maxlength": "50"}),
            "sourceLanguage": forms.Select(attrs={"class": "form-select"}),
            "targetLanguage": forms.Select(attrs={"class": "form-select"}),
        }

class New_quiz(ModelForm):
    class Meta:
        model = Quiz
        fields = ("difficulty",)

        widgets = {
            "difficulty": forms.Select(attrs={"class": "form-select form-select-lg"})
        }

class New_answer(ModelForm):
    class Meta:
        model = Answer
        fields = ("text",)

        widgets = {
            "text": forms.TextInput(attrs={"class": "form-control form-control-lg"})
        }

def index(request):
    if request.method =="POST":
        form = New_word(request.POST)
        if form.is_valid():

            new_word_form = form.save(commit=False)

            # Sending request to the API
            url = "https://text-translator2.p.rapidapi.com/translate"
            headers = {
                "content-type": "application/x-www-form-urlencoded",
                "X-RapidAPI-Key": API_KEY,
                "X-RapidAPI-Host": "text-translator2.p.rapidapi.com"
            }
            payload = {
                "source_language": new_word_form.sourceLanguage,
                "target_language": new_word_form.targetLanguage,
                "text": new_word_form.text,
                
            }
            
            response = requests.post(url, data=payload, headers=headers)
            new_word_form.timestamp = datetime.now() 
            new_word_form.translation = response.json()["data"]["translatedText"].lower()
            new_word_form.translation_edited = response.json()["data"]["translatedText"].lower()
            new_word_form.user = request.user
            new_word_form.text = new_word_form.text.lower()
            new_word_form.save()
            return HttpResponseRedirect(reverse('index'))

    else:
        words = NewWord.objects.filter(user = request.user).order_by('-timestamp')
        p = Paginator(words, 20)
        page = request.GET.get('page')
        page_obj = p.get_page(page)
        return render(request, "AdvancedDict/index.html", {
            "form": New_word,
            "page": page_obj,
            "dict": languageCodes.languages_to_countries_dict,
            })

@csrf_exempt
@login_required
def generate_quiz(request):
    if request.method == "POST":
        form = New_quiz(request.POST)
        if form.is_valid:
            new_quiz_form = form.save(commit=False)
            new_quiz_form.timestamp = datetime.now(tz=None)
            new_quiz_form.user = request.user
            new_quiz_form.save()
            print(new_quiz_form.pk)
            return HttpResponseRedirect(f"{new_quiz_form.pk}")
    else:
        return render(request, "AdvancedDict/newQuiz.html", {
            "form": New_quiz
        })

@csrf_exempt
@login_required
def get_quiz(request, quiz_id):

    quiz = Quiz.objects.get(pk = quiz_id)

    if request.user != quiz.user:
        return HttpResponse(status=400)
    
    if request.method == "POST":    

        form = New_answer(request.POST)
        if form.is_valid:
            new_answer_form = form.save(commit=False)
            q_pk = request.POST.get("question")
            
            # Making quiz more user-friendly, so it checks if answer is correct for any words with same translation
            # print(q_pk)
            temp_word = NewWord.objects.get(pk = q_pk)
            print(temp_word)
            new_answer_form.question = temp_word
            new_answer_form.asked = temp_word.translation_edited
            matching_values = NewWord.objects.filter(translation_edited=temp_word.translation_edited).values_list("text", flat=True)
            print("Correct",matching_values)
            print("answer:",new_answer_form.text.lower())
            if new_answer_form.text.lower() in list(matching_values):
                print("right!")
                new_answer_form.correct = True
            new_answer_form.save()

            # linking answer to quiz
            quiz.answers.add(new_answer_form)
            # print(request.POST)
            page = int(request.POST.get("page", 1))
            print("page", page)

            if "final" in request.POST:
                # Updating quiz score onsubmit
                answers_score = sum(list(quiz.answers.all().values_list("correct", flat=True)))
                quiz.score = answers_score
                print(quiz.score)
                quiz.save()
                return HttpResponseRedirect(reverse("report quiz", kwargs={"quiz_id": quiz_id}))
            return HttpResponseRedirect(reverse("display quiz", kwargs={"quiz_id": quiz_id}) + f"?page={page+1}")

        # if form is invalid
        else:
            return HttpResponse(status=400)
        
    else:    
        question_count = quiz.questions.all().count()
        # print("diff" ,quiz.difficulty)
        # print("count", question_count)
        if question_count < quiz.difficulty:
            words = NewWord.objects.values_list('pk', flat=True).filter(user = request.user)
            # words = NewWord.objects.filter(user = request.user)
            # print(words)
            for _ in range(quiz.difficulty):
                # print(random.choice(words))
                indx = random.choice(words)
                # words.exclude(indx)
                quiz.questions.add(NewWord.objects.get(pk = indx))

        p = Paginator(quiz.questions.all().order_by('pk'), 1)
        page = request.GET.get('page')
        page_obj = p.get_page(page)
        # print(quiz.questions.all())
        return render(request, "AdvancedDict/quizDisplay.html", {
            "quiz": quiz,
            "page": page_obj,
            "dict": languageCodes.languages_to_countries_dict,
            "form": New_answer
        })

@login_required
def report_quiz(request, quiz_id):

    quiz = Quiz.objects.get(pk = quiz_id)

    if request.user != quiz.user:
        return HttpResponse(status=400)
    
    return render(request, "AdvancedDict/quizReport.html", {
        "dict": languageCodes.languages_to_countries_dict,
        "quiz": quiz,
        "answers": quiz.answers.all(),
        "percent": f"{(float(quiz.score) / float(quiz.answers.all().count()))*100:.1f}",
    })

@login_required
def all_reports(request):
    quizes = Quiz.objects.filter(score__isnull = False , user = request.user).order_by('-timestamp')
    return render(request, "AdvancedDict/allReports.html", {
        "quizes": quizes
    })

@csrf_exempt
@login_required
def edit(request, word_id):
    try: 
        word = NewWord.objects.get(pk = word_id)
    except NewWord.DoesNotExist:
        return JsonResponse({"error": "Word does not exist."}, status=404)
    
    # in case of attempt to access another user post
    if request.user != word.user:
        return JsonResponse({"error": "Cannot edit another user's word."}, status=404)
    
    if request.method == "PUT":
        data = json.loads(request.body) 
        if data.get("translation") is not None:
            word.translation_edited = data["translation"].lower()
            word.save()
            return HttpResponse(status=204)
        else:
            return JsonResponse({"error": "Invalid request"}, status=400)

    elif request.method == "DELETE":
        word.delete()
        return HttpResponse(status=204)


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "AdvancedDict/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "AdvancedDict/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "AdvancedDict/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "AdvancedDict/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:

AdvancedDict/templates/AdvancedDict/allReports.html
{% extends "AdvancedDict/layout.html" %}
{% load static %}
{% load tags_extra %}

{% block body %}



<div class="container-lg" style="margin-top: 30px;">
    <div class="row align-items-start">
    {% if user.is_authenticated %}        
    <br><h1 style="margin-bottom: 20px; margin-top: 40px;">Quizes</h1>
    <div class="row align-items-start" >
        <div class="row">
            
            <div class="col-2" style="width: 16%;"><h5>Difficulty</h5></div>
            <div class="col-2" style="margin-left: 6px;"><h5>Score</h5></div>
            <div class="col-2" style="margin-left: 10px;"><h5>Timestamp</h5></div></div></div><hr style="margin-top: 4px; margin-bottom: 0px;">

    {% for quiz in quizes %}  
    <a href="{% url 'report quiz' quiz.id%}">
    <div class="row align-items-center block" data-correct="{{answer.correct}}" style="padding-bottom: 12px; padding-top: 12px; ">

        <div class="col-2" style="width: 16%;">
        <strong>{{quiz.get_difficulty_display}}</strong></div>
      
        <div class="col-2">
        <strong data-translation="{{word.translation}}">{{quiz.score}} of {{quiz.answers.count}}</strong></div>
        <div class="col-2">{{quiz.timestamp}}</div>
    </div><hr style="margin-bottom: 0px;"></a>
 
    {% endfor %}
    </div></div>
    {% endif %}
    {% endblock %}

AdvancedDict/templates/AdvancedDict/index.html
{% extends "AdvancedDict/layout.html" %}
{% load static %}
{% load tags_extra %}

{% block body %}
<div class="container-lg">
{% if user.is_authenticated %}
{% if page.number == 1%}
    <form method="post" style="margin-top: 40px; margin-bottom: 0px;" action="{% url 'index' %}">
        {% csrf_token %}
        {{ form }}
        <br>
        <input type="submit" class="btn btn-outline-primary">
    </form>
    {% endif %}
    {% if page %} <br><h1 style="margin-bottom: 20px;">Words</h1>
    <div class="row align-items-start" data-id="{{word.id}}">
        <div class="row">
            
            <div class="col-2" style="width: 16%;"><h5>From</h5></div>
            <div class="col-2"><h5>To</h5></div></div></div><hr style="margin-top: 4px;">
    {% endif%}
    <div style="margin-top: 5px;">
    {% for word in page %}
    <div class="row align-items-center" data-id="{{word.id}}" st>
        <div class="row align-items-center">

            <div class="col-2" style="width: 16%;">
            <img src="https://flagcdn.com/48x36/{{ dict|newitem:word.sourceLanguage }}.png" alt="{{ word.get_sourceLanguage_display }} Flag" height="16">
            <!--{{word.get_sourceLanguage_display}}-->
            <strong class="wordText">{{word.text|capfirst}}</strong></div>
 
            <div class="col-3">
            <img src="https://flagcdn.com/48x36/{{ dict|newitem:word.targetLanguage }}.png" alt="{{ word.get_targetLanguage_display }} Flag" height="16">
            {{word.get_targetLanguage_display}}
            <span class="wordTranslation"  style="text-transform: capitalize;">
            <strong>{{word.translation_edited|capfirst}}</strong>
            <span class="forform"></span>
            </span><span class="translation" data-translation="{{word.translation}}" style="text-transform: capitalize;"></span></div>
            <div class="col buttoncol" style="text-align: right; margin-right: 12px;">
                <button class="btn btn-outline-primary btn-sm" style="margin-right: 2px;">Translation</button>
                <button class="btn btn-outline-secondary btn-sm" style="margin-right: 2px;">Edit</button>
                <button class="btn btn-outline-danger btn-sm">Delete</button>
            </div>
        </div>
        <hr style="margin-top: 12px;">
    </div>
    {%empty%}
    <br><h4 style="margin-top: 36px;">Words you add will display here...</h4><hr>
    {% endfor%}
    </div>
    <!--Paginator-->
    {% if page.paginator.num_pages > 1 %} 
    <div class="pagination" style="margin-top: 24px;">
        <span class="step-links">
            <ul class="pagination justify-content-center"">
            {% if page.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="Previous">{{ page.previous_page_number }}</a></li>
                <!--<a href="?page={{ page.previous_page_number }}">previous</a>-->
            {% endif %}

            <span class="current">
                <li class="page-item active"><a class="page-link" href="?page={{ page }}" aria-label="Previous">{{ page.number }}</a></li>
            </span>

            {% if page.has_next %}
            <!--<a href="?page={{ page.next_page_number }}">next</a>
            <a href="?page={{ page.paginator.num_pages }}">last &raquo;</a>-->
            <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Previous">{{ page.next_page_number }}</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">Last</a></li>
            {% endif %}
        </span>
          </ul>
    </div>
    {% endif %}

{% endif %}
</div>
{% endblock %}

AdvancedDict/templates/AdvancedDict/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}MegaDict{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <link href="{% static 'AdvancedDict/styles.css' %}" rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <script src="https://kit.fontawesome.com/46ec4db9a1.js" crossorigin="anonymous"></script>
        <script src="{% static 'AdvancedDict/words.js'%}"></script> 
    </head>
    <body style="background-color: #fafafa; color: #2a2626;"></body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-lg">
            <a class="navbar-brand mb-0 h1" href="{% url 'index' %}" style="font-weight: 600;">OmegaDict</a>
          
            <div>
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'generate quiz' %}"><strong>Quiz</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'index' %}">Words</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reports' %}">Quiz Reports</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout'%}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login'%}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
            </div>
          </nav>
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

AdvancedDict/templates/AdvancedDict/login.html
{% extends "AdvancedDict/layout.html" %}
{% load static %}
{% block body %}
    <div class="container-lg">
    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    <div style="padding-top: 6px;"> Don't have an account? <a href="{% url 'register' %}">Register here.</a></div>
    </div>
{% endblock %}

AdvancedDict/templates/AdvancedDict/newQuiz.html
{% extends "AdvancedDict/layout.html" %}
{% load static %}
{% load tags_extra %}

{% block body %}
<div class="container-lg">
{% if user.is_authenticated %}
    <form method="post" style="margin-top: 120px;" action="{% url 'generate quiz' %}">
        {% csrf_token %}
        {{ form }}
        <input type="submit" class="btn btn-primary btn-lg" value="Start">
    </form>
{% endif %}
</div>
{% endblock %}

AdvancedDict/templates/AdvancedDict/quizDisplay.html
{% extends "AdvancedDict/layout.html" %}
{% load static %}
{% load tags_extra %}

{% block body %}
<div class="container-lg" style="margin-top: 120px;">
    <div class="row align-items-start" style="margin-top: 80px;">
    {% if user.is_authenticated %}
    {%for question in page%}
        <div class="col-3" style="text-align: center;">
        <h5 style="margin-top: 12px; margin-bottom: 6px;">Translate</h5>
        <h3>{{question.translation_edited|capfirst}}</h3> 
        
        <h5 style="margin-bottom: 15px;">
        to
        <img src="https://flagcdn.com/48x36/{{ dict|newitem:question.sourceLanguage }}.png" alt="{{ question.get_sourceLanguage_display }} Flag" height="16">
        {{question.get_sourceLanguage_display}}</h5></div>
        <div class="col-9">
            <form class="form=control" action="{% url 'display quiz' quiz.id %}" method="post"> {{form}} 
                <input type="hidden" value="{{question.id}}" name="question"> </input>
                {% if page.has_next%}
                <input type="hidden" value="{{page.number}}" name="page"> </input>
                <input type="submit" value="Next"class="btn btn-primary" style="margin-top: 20px;"></input>
                {% else %}
                <input type="hidden" value="true" name="final"> </input>
                <input type="submit" value="Submit" class="btn btn-primary" style="margin-top: 20px;"></input>
                {% endif %}
            </form> </div>
            </div>
    {% endfor %}
    <!--
    {% if page.paginator.num_pages > 1 %} 
    <div class="pagination" style="margin-top: 48px; margin-left: 7.7%">
        <span class="step-links">
            <ul class="pagination justify-content-center pagination-lg">
              
            {% if page.has_next %}
            <!--<a href="?page={{ page.next_page_number }}">next</a>
            <a href="?page={{ page.paginator.num_pages }}">last &raquo;</a>
            <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Next" style="border-width: 3px;">
                <span style="font-weight: 550; font-size: 20px;">Next</span></a></li>
            {% endif %}
        </span>
          </ul>
    </div>
    {% endif %}
    -->
{% endif %}
</div>
{% endblock %}

AdvancedDict/templates/AdvancedDict/quizReport.html
{% extends "AdvancedDict/layout.html" %}
{% load static %}
{% load tags_extra %}

{% block body %}
<script>
    addEventListener('DOMContentLoaded', ()=>{
        document.querySelectorAll('.block').forEach((parentblock) => {
            const cor = parentblock.getAttribute("data-correct")
            if (cor == 'True') {
                //pass
            } else {
                parentblock.style.backgroundColor  = '#ff7f7f   ';

            }
        })
        
    })

</script>

<div class="container-lg" style="margin-top: 30px;">
    <div class="row align-items-start">
    {% if user.is_authenticated %}
    <h6 style="opacity: 75%; font-weight: 400; margin-bottom: 2px;">{{quiz.timestamp}}</h6>
        <h1 style="margin-bottom: 4px; margin-top: 2px;">{{percent}}%</h1>
        <h4>{{quiz.score}} out of {{quiz.answers.count}}</h4>
        
    <br><h1 style="margin-bottom: 20px; margin-top: 40px;">Answers</h1>
    <div class="row align-items-start" >
        <div class="row">
            
            <div class="col-2" style="width: 16%;"><h5>Asked</h5></div>
            <div class="col-2"><h5>Answer</h5></div></div></div><hr style="margin-top: 4px; margin-bottom: 0px;">
    {% for answer in answers %}   
    <div class="row align-items-center block" data-correct="{{answer.correct}}" style="padding-bottom: 12px; padding-top: 12px; ">

        <div class="col-2" style="width: 16%;">
        <img src="https://flagcdn.com/48x36/{{ dict|newitem:answer.question.targetLanguage }}.png" alt="{{ answer.question.get_targetLanguage_display }} Flag" height="16">
        <!--{{word.get_sourceLanguage_display}}-->
        <strong class="wordText">{{answer.question.translation_edited|capfirst}}</strong></div>

      
        <div class="col-3">
        <img src="https://flagcdn.com/48x36/{{ dict|newitem:answer.question.sourceLanguage }}.png" alt="{{ word.get_sourceLanguage_display }} Flag" height="16">
        {{word.get_sourceLanguage_display}}
        <span class="wordTranslation"  style="text-transform: capitalize;">
        <strong data-translation="{{word.translation}}">{{answer.text}}<span></span></strong>
        <span></span>
        </span></div></div><hr style="margin-bottom: 0px;">
 
    {% endfor %}
    </div>
    <!--
    {% if page.paginator.num_pages > 1 %} 
    <div class="pagination" style="margin-top: 48px; margin-left: 7.7%">
        <span class="step-links">
            <ul class="pagination justify-content-center pagination-lg">
              
            {% if page.has_next %}
            <!--<a href="?page={{ page.next_page_number }}">next</a>
            <a href="?page={{ page.paginator.num_pages }}">last &raquo;</a>
            <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Next" style="border-width: 3px;">
                <span style="font-weight: 550; font-size: 20px;">Next</span></a></li>
            {% endif %}
        </span>
          </ul>
    </div>
    {% endif %}
    -->
{% endif %}
</div>
{% endblock %}

    <!--
    {% if page.paginator.num_pages > 1 %} 
    <div class="pagination" style="margin-top: 48px; margin-left: 7.7%">
        <span class="step-links">
            <ul class="pagination justify-content-center pagination-lg">
              
            {% if page.has_next %}
            <!--<a href="?page={{ page.next_page_number }}">next</a>
            <a href="?page={{ page.paginator.num_pages }}">last &raquo;</a>
            <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Next" style="border-width: 3px;">
                <span style="font-weight: 550; font-size: 20px;">Next</span></a></li>
            {% endif %}
        </span>
          </ul>
    </div>
    {% endif %}
    -->

AdvancedDict/templates/AdvancedDict/register.html
{% extends "AdvancedDict/layout.html" %}
{% load static %}
{% block body %}
    <div class="container-lg">
    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    <div style="padding-top: 6px;">Already have an account? <a href="{% url 'login' %}">Log In here.</a></div>
    </div>
{% endblock %}